In [1]:
import numpy as np
import pandas as pd
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [9]:
string_data.isnull()    # 是否为空 

0    False
1    False
2     True
3    False
dtype: bool

In [10]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()   # 过滤掉 NA  === data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [14]:
data = pd.DataFrame([[1., 6.5, 3.],
                     [1, NA, NA],
                     [NA, NA, NA],
                     [NA, 6.5, 3.]])
cleaned = data.dropna()

In [15]:
data     # dropna 不会 改原数据

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [18]:
cleaned_all = data.dropna(how='all')   # 一行全部为 NA的才丢弃   axis=1  可以丢弃列 
cleaned_all 

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [71]:
# 
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0  0.010967       NaN       NaN
1 -0.062568       NaN       NaN
2 -0.088586       NaN  0.128746
3  0.148533       NaN  0.481490
4 -0.565491  1.159788 -0.753594
5 -0.902740  0.926324  0.538692
6  1.181938  0.402729 -0.305084

In [72]:
df.dropna()

0         1         2
4 -0.565491  1.159788 -0.753594
5 -0.902740  0.926324  0.538692
6  1.181938  0.402729 -0.305084

In [73]:
df.dropna(thresh=2)   # 行中数据不是NA 的个数 

0         1         2
2 -0.088586       NaN  0.128746
3  0.148533       NaN  0.481490
4 -0.565491  1.159788 -0.753594
5 -0.902740  0.926324  0.538692
6  1.181938  0.402729 -0.305084

In [74]:
# 填充NA值
df.fillna(0)

0         1         2
0  0.010967  0.000000  0.000000
1 -0.062568  0.000000  0.000000
2 -0.088586  0.000000  0.128746
3  0.148533  0.000000  0.481490
4 -0.565491  1.159788 -0.753594
5 -0.902740  0.926324  0.538692
6  1.181938  0.402729 -0.305084

In [75]:
df

0         1         2
0  0.010967       NaN       NaN
1 -0.062568       NaN       NaN
2 -0.088586       NaN  0.128746
3  0.148533       NaN  0.481490
4 -0.565491  1.159788 -0.753594
5 -0.902740  0.926324  0.538692
6  1.181938  0.402729 -0.305084

In [76]:
df.fillna({1:0.5, 2:0})   # 针对列

0         1         2
0  0.010967  0.500000  0.000000
1 -0.062568  0.500000  0.000000
2 -0.088586  0.500000  0.128746
3  0.148533  0.500000  0.481490
4 -0.565491  1.159788 -0.753594
5 -0.902740  0.926324  0.538692
6  1.181938  0.402729 -0.305084

In [84]:
df = pd.DataFrame(np.random.randn(6,3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0         1         2
0  1.946820  0.021777  0.440236
1 -0.487014 -2.019738  0.012280
2 -0.828083       NaN  0.254733
3 -0.809780       NaN -1.847850
4  0.875132       NaN       NaN
5  0.484864       NaN       NaN

In [85]:
df.fillna(method='ffill')  # 和之前学的reindexing 

0         1         2
0  1.946820  0.021777  0.440236
1 -0.487014 -2.019738  0.012280
2 -0.828083 -2.019738  0.254733
3 -0.809780 -2.019738 -1.847850
4  0.875132 -2.019738 -1.847850
5  0.484864 -2.019738 -1.847850

In [86]:
df.fillna(method='ffill', limit=2)

0         1         2
0  1.946820  0.021777  0.440236
1 -0.487014 -2.019738  0.012280
2 -0.828083 -2.019738  0.254733
3 -0.809780 -2.019738 -1.847850
4  0.875132       NaN -1.847850
5  0.484864       NaN -1.847850

In [87]:
data = pd.Series([1, NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [89]:
# 移除重复数据
data = pd.DataFrame({'k1':['one', 'two'] *3 + ['two'], 'k2':[1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [90]:
data.duplicated()   # 返回一个Series bool型

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [91]:
data.drop_duplicates()   # 返回一个DataFrame  将重复的行去掉  

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [96]:
data['v1'] = range(7)
print(data)
data.drop_duplicates(['k1'])  # 以k1为列作为筛选参考  默认保留第一个出现的  keep='last' 保留最后一个

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6


k1  k2  v1
0  one   1   0
1  two   1   1

In [97]:
# 数据转换  函数映射 
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon','Pastrami', 'corned beef', 'Bacon','pastrami', 'honey ham', 'nova lox'],
                     'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [98]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [99]:
data['animal'] = lowercased.map(meat_to_animal)   #分类
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [102]:
data['food'].map(lambda x: meat_to_animal[x.lower()])  # 使用map是一种实现元素级转换以及其他数据清理工作的便捷方式

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [104]:
# 替换值 
data = pd.Series([1., -999., 2., -999., -1000., 3.])
print(data)
data.replace(-999, np.nan)

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64


0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [105]:
data.replace([-999, -1000], np.nan)  # 多个替换值

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [107]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [108]:
data.replace({-999 : np.nan, -1000 : 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [109]:
# 轴索引 
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data.index.map(lambda x: x[:4].upper())   #  这样并未修改原索引

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [113]:
data.index = data.index.map(lambda x: x[:4].upper())
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [117]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [119]:
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'})  #这应该是万机油了 

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [124]:
# 离散化和 面元划分
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
# 划分为 18到20   26到35   35到60   60以上

[20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [126]:
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [127]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [128]:
cats.categories   # closed表示右闭区间

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]]
              closed='right',
              dtype='interval[int64]')

In [129]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [131]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [MiddleAged < Senior < YoungAdult < Youth]

In [132]:
data = np.random.rand(20)
pd.cut(data, 4, precision=2)   #均匀分布成四组   precision=2 表示限定小数只有俩位 

[(0.023, 0.24], (0.45, 0.66], (0.023, 0.24], (0.66, 0.87], (0.45, 0.66], ..., (0.66, 0.87], (0.45, 0.66], (0.66, 0.87], (0.66, 0.87], (0.45, 0.66]]
Length: 20
Categories (4, interval[float64]): [(0.023, 0.24] < (0.24, 0.45] < (0.45, 0.66] < (0.66, 0.87]]

In [135]:
data = np.random.randn(1000)
cats = pd.qcut(data, 4)
cats.value_counts()   # 花费成大小相等的面元

(-2.722, -0.765]     250
(-0.765, -0.0371]    250
(-0.0371, 0.644]     250
(0.644, 4.143]       250
dtype: int64

In [148]:
# pd.qcut(data, [0, 0,1, 0.5, 0.9, 1.] )  # 不知道为什么不能用 

In [150]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.048273     0.016618     0.015116    -0.064005
std       0.991392     0.982913     1.067948     0.998605
min      -3.031984    -3.264100    -3.480969    -3.552227
25%      -0.646497    -0.628695    -0.683290    -0.731814
50%       0.046137    -0.034876     0.031949    -0.071538
75%       0.738475     0.661385     0.737318     0.628858
max       2.607156     3.047562     2.896308     3.122552

In [151]:
col = data[2]
col[np.abs(col) > 3]  # 绝对值大于3 的行 

123   -3.480969
736   -3.199239
Name: 2, dtype: float64

In [159]:
data[(np.abs(data) > 3).any(1)]   # 这里的any只能是1   试了0和2都报错   any(1)表示只要是任意一行有符合条件的  

0         1         2         3
123 -0.813509 -0.498439 -3.480969 -0.720743
211  1.391716 -0.044448 -0.986591  3.122552
388  0.793663 -3.264100  0.287936  0.931680
412 -0.609172  3.047562  0.703750  1.008846
502 -0.017353  1.571844  1.742801 -3.228273
736 -0.018244  2.293437 -3.199239  1.551734
846 -3.031984 -1.686385  2.620731 -2.254972
886  0.676856  0.899506 -0.209611 -3.552227

In [161]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.048305     0.016835     0.015796    -0.063347
std       0.991293     0.981920     1.065896     0.995741
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.646497    -0.628695    -0.683290    -0.731814
50%       0.046137    -0.034876     0.031949    -0.071538
75%       0.738475     0.661385     0.737318     0.628858
max       2.607156     3.000000     2.896308     3.000000

In [163]:
# 排列和随机采样
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))
sampler = np.random.permutation(5)
sampler

array([2, 1, 4, 3, 0])

In [164]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [165]:
df.take(sampler)

0   1   2   3
2   8   9  10  11
1   4   5   6   7
4  16  17  18  19
3  12  13  14  15
0   0   1   2   3

In [172]:
df.sample(n=3)  # 随机选俩行的 

0   1   2   3
4  16  17  18  19
1   4   5   6   7
3  12  13  14  15

In [176]:
# 指标/哑变量
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],'data1': range(6)})
print(df)
pd.get_dummies(df['key'])

   data1 key
0      0   b
1      1   b
2      2   a
3      3   c
4      4   a
5      5   b


a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [178]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [180]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('datasets/movielens/movies.dat', sep='::',header=None, names=mnames)
movies[:10]

/Users/jack/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  


movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [181]:
all_genres=[]
for x in movies.genres:
    all_genres.extend(x.split('|'))
genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [182]:
zero_mtx = np.zeros((len(movies), len(genres)))
dummies = pd.DataFrame(zero_mtx, columns=genres)
gen = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [183]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2])

In [184]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [185]:
np.random.seed(12345)
values = np.random.rand(10)
values

array([ 0.92961609,  0.31637555,  0.18391881,  0.20456028,  0.56772503,
        0.5955447 ,  0.96451452,  0.6531771 ,  0.74890664,  0.65356987])

In [188]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [189]:
# 字符串操作
val = 'a,b,  guido'
val.split(',')

['a', 'b', '  guido']

In [190]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [191]:
s1, s2, s3 = pieces
s1 + '::' + s2 + '::' + s3

'a::b::guido'

In [192]:
'::'.join(pieces)  # 更加高效的做法 

'a::b::guido'

In [195]:
'guido' in val

True

In [196]:
val.index(',')

1

In [197]:
val.find(':')

-1

In [198]:
val.index(':')   # 如果没有找到就报错

ValueError: substring not found

In [200]:
val.count(',')

2

In [201]:
val.replace(',', '::')

'a::b::  guido'

In [202]:
val.replace(',', '')

'ab  guido'

In [204]:
# 正则表达式   模式匹配   替换  拆分 
import re 
text = "foo bar\t baz    \tqux"
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [205]:
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [206]:
regex.findall(text)

[' ', '\t ', '    \t']

In [208]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'

# re.IGNORECASE makes the regex case-insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [209]:
m = regex.search(text)  # 返回的是第一个符合条件的
m

<_sre.SRE_Match object; span=(5, 20), match='dave@google.com'>

In [210]:
text[m.start() : m.end()]

'dave@google.com'

In [211]:
print(regex.sub('READCTED', text))

Dave READCTED
Steve READCTED
Rob READCTED
Ryan READCTED



In [213]:
pattern = r'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})'
regex = re.compile(pattern, flags=re.IGNORECASE)
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [214]:
m = regex.match('wesm@bright.net')
m.groups()

('wesm', 'bright', 'net')

In [215]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [216]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com



In [219]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com','Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data.str.contains('gmail')   # isnull()  

Dave     False
Rob       True
Steve     True
Wes        NaN
dtype: object

In [220]:
pattern

'([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\\.([A-Z]{2,4})'

In [221]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Rob        [(rob, gmail, com)]
Steve    [(steve, gmail, com)]
Wes                        NaN
dtype: object

In [224]:
match = data.str.match(pattern, flags=re.IGNORECASE)
match

Dave     True
Rob      True
Steve    True
Wes       NaN
dtype: object

In [226]:
match.str.get(1)

Dave    NaN
Rob     NaN
Steve   NaN
Wes     NaN
dtype: float64

In [ ]:
match.s