In [4]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))
%time for _ in range(10): my_arr = my_arr * 2
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

CPU times: user 16.9 ms, sys: 12.7 ms, total: 29.6 ms
Wall time: 29.8 ms
CPU times: user 657 ms, sys: 167 ms, total: 824 ms
Wall time: 834 ms


In [20]:
data = np.random.randn(2, 3)
print(data)
print('----------0----------')
data = data * 10
print(data)
print('----------1----------')
data = data + data
print(data)

[[ 0.06583303  2.66249928 -2.10880074]
 [-0.54419268  0.42552984 -0.99318141]]
----------0----------
[[  0.65833027  26.62499281 -21.08800741]
 [ -5.44192681   4.2552984   -9.93181413]]
----------1----------
[[  1.31666054  53.24998561 -42.17601483]
 [-10.88385362   8.51059679 -19.86362826]]


In [18]:
data.shape  // 行列 数

(2, 3)

In [21]:
data.dtype  // 数据类型

dtype('float64')

In [22]:
data.ndim  //行数

2

In [26]:
data1 = [2, 3, 6.5, 7, 9]
arr1 = np.array(data1)
print(arr1)
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)

[ 2.   3.   6.5  7.   9. ]
[[1 2 3 4]
 [5 6 7 8]]


In [36]:
arr0=np.zeros((2,4))
print(arr0)
arr1=np.ones((2,4))
print(arr1)
arrempty=np.empty((2,3))
print(arrempty)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [37]:
np.arange(10)    //用python内置函数返回

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr1=np.array([1,2,3], dtype=np.float64)
arr2=np.array([1,2,3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [39]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr.astype(np.int32)    // 转化数据类型

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [42]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(arr2d[:2])
print(arr2d[:2, 1:])

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
